language: node_js
sudo: required
services:
    - docker
before_install:
    - docker build -t 12684456/docker-react -f Dockerfile.dev   
scripts:
    - docker run 12684456/docker-react npm run test  
deploy:
    provider: heroku
    api_key:
      secure: "dd07ff66-023c-4ea8-87de-cd6b1d77114a"     
    app: docker-react 
    on:
        branch: master     
    